# Generated by Django 4.0.4 on 2022-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Tickets', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AlterModelOptions(
            name='ticketsmessage',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Сообщения в тикетах'},
        ),
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.CharField(default='In Progress', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_by',
            field=models.CharField(max_length=255, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketsmessage',
            name='content',
            field=models.TextField(verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='ticketsmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
    ]
